# Generated by Django 3.2.5 on 2021-07-15 22:27

import api.validators
import django.contrib.postgres.fields
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Courier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('courier_id', models.IntegerField(unique=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('courier_type', models.CharField(choices=[('foot', 'foot'), ('bike', 'bike'), ('car', 'car')], max_length=4, verbose_name='Тип курьера')),
                ('regions', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(validators=[django.core.validators.MinValueValidator(0)]), size=None, verbose_name='Регионы')),
                ('working_hours', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=11, validators=[api.validators.validate_working_time]), size=None, verbose_name='График работы курьера')),
            ],
            options={
                'verbose_name': 'Курьер',
                'verbose_name_plural': 'Курьеры',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('order_id', models.AutoField(primary_key=True, serialize=False)),
                ('weight', models.FloatField(validators=[django.core.validators.MinValueValidator(0.01), django.core.validators.MaxValueValidator(50)], verbose_name='Вес заказа')),
                ('region', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)], verbose_name='Район доставки заказа')),
                ('delivery_hours', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=11, validators=[api.validators.validate_working_time]), size=None, verbose_name='Удобное время доставки')),
                ('assign_time', models.DateTimeField(default=None, verbose_name='Время назначения заказа')),
                ('complete_time', models.DateTimeField(default=None, verbose_name='Время окончания доставки заказа')),
                ('courier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.courier', verbose_name='Курьер, доставляющий заказ')),
            ],
            options={
                'verbose_name': 'Заказ',
                'verbose_name_plural': 'Заказы',
            },
        ),
    ]
