# Generated by Django 3.2.5 on 2021-07-16 14:08

import api.validators
import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courier',
            name='regions',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), size=None, validators=[api.validators.validate_regions], verbose_name='Регионы'),
        ),
        migrations.AlterField(
            model_name='courier',
            name='working_hours',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=11), size=None, validators=[api.validators.validate_hours], verbose_name='График работы курьера'),
        ),
        migrations.AlterField(
            model_name='order',
            name='delivery_hours',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=11), size=None, validators=[api.validators.validate_hours], verbose_name='Удобное время доставки'),
        ),
    ]
