# Generated by Django 3.2.5 on 2021-07-16 14:27

import api.validators
import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20210716_1708'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courier',
            name='working_hours',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=11), blank=True, size=None, validators=[api.validators.validate_hours], verbose_name='График работы курьера'),
        ),
    ]
