# Generated by Django 3.2.5 on 2021-07-16 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_courier_working_hours'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='assign_time',
            field=models.DateTimeField(blank=True, default=None, null=True, verbose_name='Время назначения заказа'),
        ),
        migrations.AlterField(
            model_name='order',
            name='complete_time',
            field=models.DateTimeField(blank=True, default=None, null=True, verbose_name='Время окончания доставки заказа'),
        ),
    ]
